### ISSUE TITLE
Determine how to track and keep time

### ISSUE THREAD

**Issue by reefdog** [tvkitchen/tv-kitchen#42]
## Discussion

"Time" in the context of the TV Kitchen has two meanings; I'll describe them both, but the thrust of this issue is the second one.

### 1. Determining when the content aired.

Airtime will be important downstream when users want to do time-based analysis like "how often was the economy discussed last month?" Our two working limiting assumptions are (a) we can only provide airtime for live streams, and (b) we'll generate airtime based on when we saw the live stream rather than being able to rely on stream-provided airtime metadata.

If we can do better than either of those two assumptions — such as if users overwhelmingly want us to treat the file creation/modification dates as local file airtimes, or if live streams bake in universal timecodes that are more accurate than our "when we saw it" proxy value — then we will.

I don't think this needs much discussion at this point. Our limiting assumptions mean the decisions are fairly straightforward.

### 2. Keeping audio/video/caption streams in sync throughout the pipeline.

This isn't necessary while we're still dealing with a container like MP4 or MPEG-TS, which are built to keep these streams in sync. But once we split the streams for processing by individual appliances, we'll need to use timecoding to be able to communicate that this frame appeared at the same time as this caption and with this speaker's voice talking, etc.

**There are significant open questions here, such as:**

1. Whose responsibility is it to keep time? Does the ingestion engine generate timecodes (or elevate internal ones) during ingestion, or is that the role of the Sous Chef? Or a "timekeeper" appliance that precedes all other steps?
2. How do we expose this timecode to the pipeline? Is it part of the [`Payload`](https://github.com/tvkitchen/base/blob/master/src/Payload.js) metadata, or is it buried in the `data` bitstream itself? Does this decision change based on the composition of the `data`? (Like, if the payload is carrying `TEXT.CHARACTER` instead of a packaged MPEG-TS stream, how _could_ we decorate the character data with a timecode _without_ using the Payload metadata attributes?)
3. Does the size of an individual `Payload` affect this decision? For instance, if a `Payload`'s `data` is a single character, can we even timecode granularly enough for "timecode" to have any relevance? (It already argues for not reconstructing a stream based on timecode along; we need another way of sequencing linear data streams, but I assume that'll be handled naturally by the Kafka queue orders.)
4. Do we need separate concepts for "timecode" (used for keeping a/v/c streams in sync) and "airtime", or can timecodes be expressed in UTC (or equivalent)?

**Comment by slifty** [comment]
At first I was thinking that we might have two "modes" for ingestion engines -- one for a recorded file (where time would be relative to the start time of the file) and one for live streams (where time would be relative to unix epoch).

It would be nice, however to have a single mechanism that works for both.

With that in mind I'll take a stab on some proposed answers:

> Whose responsibility is it to keep time
I think for now lets make that the responsibility of the ingestion engine.  That way by the time (HA) data is at the countertop it has already been tagged with a time. 

The chunks of data are going to be so small that they will be true moments (e.g. functionally a duration of zero), but this is OK because the appliance model already has to account for combining chunks of data that span moments and translating that into new data types with durations.

> How do we expose timecode to the pipeline

Yes it should be part of Payload metadata.

I'm thinking there should be three things for sure, and MAYBE a fourth.  *(These names are not prescriptive)*

1. created_at (the moment in real actual time the data was sent to kafka)
2. relative_timestamp (how far into the stream / file does this data represent)
3. duration

And then maybe:

4. base_timestamp (what time did this input begin streaming this time) <-- this allows us to have streams start / stop and have relative_timestamps reset.

> Size of payload affect decision?

I don't think so.  The STREAM.DATA payloads are currently framed as arbitrary length (kind of "consume as fast as we consume).

**Comment by slifty** [comment]
I think between the Payload change and the recently closed #45 we're all set on this issue.  Ty for the exploration!
