### ISSUE TITLE
/src/lib is a bad name

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen#46]
#### What do you want to talk about?
When setting up our `src` directory we created a `lib` directory for things like kafka clients and utils.  The problem is that `lib` seems to be used to reference code that has been transpiled, which is NOT what we're referring to here.

Lets pick a better name to avoid confusion.

#### Relevant Resources / Research
[this gist alludes to the transpiling association of lib](https://gist.github.com/tracker1/59f2c13044315f88bee9)

**Comment by slifty** [comment]
It came to me in a dream: `src/tools`

thoughts?

**Comment by reefdog** [comment]
I still think it's weird that `lib/` is for transpiled code that's destined for Node instead of the browser. (Rather, the weird thing to me is that we don't just use `dist/` for all transpiled code and `lib/` for code that needs to transpilation.) (Weird, but I'm not objecting!)

I like `src/tools`! I'm going to open a PR with `src/tools/justin/pleased.jpeg`

**Comment by slifty** [comment]
Still waiting on that PR.
